### ISSUE TITLE
How do you nest menus?

### ISSUE THREAD

**Issue by danielpcox** [mbsmith/clj-systemtray#1]
Hey Michael,

I couldn't tell from the docs: how do you nest popup menus the way "Display" is nested inside the main menu here?

![image](https://cloud.githubusercontent.com/assets/56411/6336634/f2b89538-bb71-11e4-9905-f89f23b1ab3b.png)

Thanks,
-Daniel

**Comment by danielpcox** [comment]
Oh, I'm sorry. I didn't read carefully enough to notice they weren't supported.
I'll add them.

**Comment by danielpcox** [comment]
Added!
https://github.com/mbsmith/clj-systemtray/pull/2

**Comment by mbsmith** [comment]
Thanks for the PR.  Looks good to me.
