### ISSUE TITLE
README, Clojars and Marginalia docs need updating

### ISSUE THREAD

**Issue by danielpcox** [mbsmith/clj-systemtray#3]
Hey Michael,

Although the README now explains how to use nested menus, the version still points to the old 0.1.4, Clojars still only has 0.1.4, and the Marginalia docs need to be rebuilt and put up at http://mbsmith.github.io/clj-systemtray . 

To DRY up the README, I'd also recommend removing the manual dependency snippet and just let people get it from the Clojars badge.

Thanks,
-Daniel

**Comment by mbsmith** [comment]
Sorry about the delay.  I actually meant to do that and got side-tracked.  I've deployed and will update the docs asap.

**Comment by mbsmith** [comment]
Both are updated.  Closing for now.  Let me know if you have any problems.

Thanks again,
Micheal
